name: Cancer Prediction CICD pipeline



on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:

    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name : Checkout code
              uses: actions/checkout@v3
        
            - name : Set up Python
              uses: actions/setup-python@v4
              with: 
                  python-version: 3.11.9

                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            
            - name: Train the model (Online Training)
              run: |
                  ls -l
                  pwd
                  python model/model.py

            - name: Run Tests
              run: pytest
    
    deploy:
        name: Deploy to Railway
        runs-on: ubuntu-latest
        needs: build-and-test
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install Railway CLI
              run: npm install -g @railway/cli